# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{chicago}
  s.version = "0.3.13"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin 'Gus' Knowlden"]
  s.date = %q{2010-05-17}
  s.description = %q{Sinatra runtime and testing extensions used commonly by Thumblemonks. For example, :json_response, which turns an object into JSON and sets the content-type appropriately.}
  s.email = %q{gus@gusg.us}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "chicago.gemspec",
     "lib/chicago.rb",
     "lib/chicago/application.rb",
     "lib/chicago/helpers.rb",
     "lib/chicago/responders.rb",
     "lib/chicago/riot.rb",
     "lib/chicago/riot/macros.rb",
     "test/application_test.rb",
     "test/helpers_test.rb",
     "test/responders_test.rb",
     "test/riot_macros_test.rb",
     "test/teststrap.rb"
  ]
  s.homepage = %q{http://github.com/thumblemonks/chicago}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Sinatra runtime and testing extensions used commonly by Thumblemonks}
  s.test_files = [
    "test/application_test.rb",
     "test/helpers_test.rb",
     "test/responders_test.rb",
     "test/riot_macros_test.rb",
     "test/teststrap.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<riot>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
    else
      s.add_dependency(%q<riot>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
    end
  else
    s.add_dependency(%q<riot>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
  end
end

